//! v0 compatibility artifacts: `/etc/resolv.conf` and `/etc/hosts`, rendered
//! from what netd knows. Scaffolding until resolvd (PEI-498) — which drops
//! `/etc/hosts` and ships a constant `resolv.conf` — replaces them.

use std::net::Ipv4Addr;
use std::path::Path;

use crate::log;

#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct DnsFacts {
    pub servers: Vec<Ipv4Addr>,
    pub search: Vec<String>,
}

pub fn resolv_conf(facts: &DnsFacts) -> String {
    let mut s = String::from("# Generated by netd from the registry and DHCP; edits are overwritten.\n");
    for server in facts.servers.iter().take(3) {
        s.push_str(&format!("nameserver {server}\n"));
    }
    if !facts.search.is_empty() {
        s.push_str("search ");
        s.push_str(&facts.search.iter().take(6).cloned().collect::<Vec<_>>().join(" "));
        s.push('\n');
    }
    s.push_str("options edns0\n");
    s
}

pub fn hosts(hostname: &str, extra: &[(String, String)]) -> String {
    let mut s = String::from("# Generated by netd from Machine\\System\\Network\\Resolver\\Hosts; edits are overwritten.\n");
    s.push_str("127.0.0.1 localhost\n::1 localhost\n");
    if !hostname.is_empty() && hostname != "localhost" {
        s.push_str(&format!("127.0.1.1 {hostname}\n"));
    }
    for (name, addr) in extra {
        s.push_str(&format!("{addr} {name}\n"));
    }
    s
}

/// Write only when the content changed, atomically.
pub fn write_if_changed(path: &str, content: &str) {
    let path = Path::new(path);
    if std::fs::read_to_string(path).map(|c| c == content).unwrap_or(false) {
        return;
    }
    let tmp = path.with_extension("netd-new");
    if let Err(e) = std::fs::write(&tmp, content).and_then(|_| std::fs::rename(&tmp, path)) {
        log::warn(format_args!("could not write {}: {e}", path.display()));
        let _ = std::fs::remove_file(&tmp);
    } else {
        log::info(format_args!("wrote {}", path.display()));
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn renders() {
        let f = DnsFacts { servers: vec![Ipv4Addr::new(10, 0, 2, 3)], search: vec!["lan".into()] };
        let r = resolv_conf(&f);
        assert!(r.contains("nameserver 10.0.2.3\n"));
        assert!(r.contains("search lan\n"));
        let h = hosts("box", &[("printer".into(), "10.0.0.9".into())]);
        assert!(h.contains("127.0.1.1 box\n"));
        assert!(h.contains("10.0.0.9 printer\n"));
    }
}
