//! What netd writes back to the registry, and the few values it shares
//! with the operator.
//!
//! Ownership is by key. `Interfaces\<ifid>\Status` and
//! `Networks\<netid>\Status` are netd's: created with a descriptor that
//! lets only SYSTEM write, so a hand edit is refused rather than silently
//! reverted at the next pass. The keys above them are the operator's,
//! except three *shared* values both may write and both mean the same
//! thing by — `Network Duid`, `Interfaces\<ifid> ClientId`,
//! `Networks\<netid> RequestedAddress` — generated by netd when absent,
//! rewritten by netd when the network hands out something new.
//!
//! `Readiness` is written on `Network` (the machine) and on each joined
//! interface's `Status`: not a PNP statement, a fact for services and
//! scripts to watch.

use std::net::Ipv4Addr;

use libnetd::{Level, NETWORK_KEY};
use peios::registry::{CreateFlags, Disposition, Key, KeyAccess, SecInfo, ValueType};

use crate::config::{format_hex, parse_hex};
use crate::log;
use crate::model::{Identity, Link, format_mac};
use crate::networks::{Record, Signals};

/// Everything a joined, ignored or down interface says about itself.
pub struct InterfaceRecord<'a> {
    pub ifid: &'a str,
    pub link: &'a Link,
    pub identity: &'a Identity,
    /// `JOIN`, `IGNORE`, `DOWN`, or `None` when no rule spoke.
    pub verdict: Option<&'a str>,
    /// The rule path that spoke.
    pub rule: Option<&'a str>,
    /// The profile path, `JOIN` only.
    pub profile: Option<&'a str>,
    /// Readiness, joined interfaces only.
    pub readiness: Option<Level>,
    /// The network record identified on this interface right now: set
    /// when the network is identified, cleared when the carrier goes.
    /// The kernel reads it for the packet layers' `Network.*` facts, so
    /// it must never name a network the link is not on.
    pub network: Option<&'a str>,
}

/// Only SYSTEM writes a `Status` key; everyone reads it. Protected, so
/// the hive root's inheritable grant to Administrators does not reach it.
const STATUS_SDDL: &str = "O:SYG:SYD:P(A;;KA;;;SY)(A;;KR;;;WD)";

const ACCESS: KeyAccess = KeyAccess::QUERY_VALUE
    .union(KeyAccess::SET_VALUE)
    .union(KeyAccess::CREATE_SUB_KEY)
    .union(KeyAccess::ENUMERATE_SUB_KEYS);

fn open_or_create(parent: Option<&Key>, name: &str) -> peios::Result<(Key, Disposition)> {
    Key::create(
        parent,
        name,
        ACCESS | KeyAccess::WRITE_DAC | KeyAccess::WRITE_OWNER,
        CreateFlags::empty(),
        None,
        None,
    )
}

/// The `Status` key under `parent`: created with netd's descriptor the
/// first time, opened afterwards.
fn status_key(parent: &Key, what: &str) -> Option<Key> {
    match open_or_create(Some(parent), "Status") {
        Ok((key, Disposition::CreatedNew)) => {
            match peios::security::sddl::parse(STATUS_SDDL) {
                Ok(sd) => {
                    if let Err(e) =
                        key.set_security(SecInfo::OWNER | SecInfo::GROUP | SecInfo::DACL, &sd, None)
                    {
                        log::warn(format_args!("{what}: could not protect Status: {e}"));
                    }
                }
                Err(e) => log::warn(format_args!("{what}: bad Status descriptor: {e}")),
            }
            Some(key)
        }
        Ok((key, _)) => Some(key),
        Err(e) => {
            log::warn(format_args!("{what}: could not open Status: {e}"));
            None
        }
    }
}

fn current(key: &Key, name: &str) -> Option<String> {
    let v = key.query_value(name.as_bytes(), None).ok()?;
    let end = v.data.iter().position(|&b| b == 0).unwrap_or(v.data.len());
    String::from_utf8(v.data[..end].to_vec()).ok()
}

fn set_sz(key: &Key, name: &str, value: &str) {
    if current(key, name).as_deref() == Some(value) {
        return;
    }
    let mut data = value.as_bytes().to_vec();
    data.push(0);
    if let Err(e) = key.set_value(name.as_bytes(), ValueType::SZ, &data).call() {
        log::warn(format_args!("inventory: could not set {name}: {e}"));
    }
}

fn set_multi(key: &Key, name: &str, values: &[String]) {
    let mut data = Vec::new();
    for v in values {
        data.extend_from_slice(v.as_bytes());
        data.push(0);
    }
    data.push(0);
    if let Ok(v) = key.query_value(name.as_bytes(), None)
        && v.ty == ValueType::MULTI_SZ
        && v.data == data
    {
        return;
    }
    if let Err(e) = key
        .set_value(name.as_bytes(), ValueType::MULTI_SZ, &data)
        .call()
    {
        log::warn(format_args!("inventory: could not set {name}: {e}"));
    }
}

/// Sets a value, or removes it when `value` is `None` (a fact that no
/// longer holds — readiness on an interface no longer joined).
fn set_opt_sz(key: &Key, name: &str, value: Option<&str>) {
    match value {
        Some(v) => set_sz(key, name, v),
        None => {
            if current(key, name).is_some() {
                let _ = key.delete_value(name.as_bytes(), None, None);
            }
        }
    }
}

fn network_key() -> Option<Key> {
    // The registry creates one level per call, so open (or make) each
    // ancestor in turn rather than asking for the leaf by full path.
    match open_or_create(None, NETWORK_KEY) {
        Ok((k, _)) => Some(k),
        Err(e) => {
            log::warn(format_args!("inventory: could not open {NETWORK_KEY}: {e}"));
            None
        }
    }
}

fn interface_key(ifid: &str) -> Option<Key> {
    let network = network_key()?;
    let (interfaces, _) = open_or_create(Some(&network), "Interfaces").ok()?;
    open_or_create(Some(&interfaces), ifid).ok().map(|(k, _)| k)
}

/// Write an interface's record under `Status`.
pub fn sync(record: &InterfaceRecord<'_>) {
    let Some(key) = interface_key(record.ifid) else {
        return;
    };
    let Some(status) = status_key(&key, record.ifid) else {
        return;
    };
    set_sz(&status, "Name", &record.link.name);
    set_sz(&status, "Kind", record.link.kind.as_str());
    set_opt_sz(
        &status,
        "Mac",
        record.link.mac.as_ref().map(format_mac).as_deref(),
    );
    set_opt_sz(
        &status,
        "Path",
        Some(record.identity.path.as_str()).filter(|s| !s.is_empty()),
    );
    set_opt_sz(
        &status,
        "Driver",
        Some(record.identity.driver.as_str()).filter(|s| !s.is_empty()),
    );
    set_opt_sz(&status, "Verdict", record.verdict);
    set_opt_sz(&status, "Rule", record.rule);
    set_opt_sz(&status, "Profile", record.profile);
    set_opt_sz(&status, "Readiness", record.readiness.map(Level::as_str));
    set_opt_sz(&status, "Network", record.network);
    // `LastNetwork` is sticky: it names the record the link last stood
    // on, which is where the next DHCP request finds `RequestedAddress`,
    // so it survives the carrier going and netd restarting.
    if let Some(network) = record.network {
        set_sz(&status, "LastNetwork", network);
    }
}

/// The interface's DHCPv4 client identifier: the operator's if written,
/// else `generate()`'s, written back so the next boot asks as the same
/// client and a server-side reservation has something to match.
pub fn client_id(ifid: &str, generate: impl FnOnce() -> Vec<u8>) -> Vec<u8> {
    let key = interface_key(ifid);
    if let Some(k) = &key
        && let Some(s) = current(k, "ClientId")
    {
        match parse_hex(&s) {
            Some(id) if !id.is_empty() => return id,
            _ => log::warn(format_args!(
                "{ifid}: ClientId {s:?} is not hex; regenerating"
            )),
        }
    }
    let id = generate();
    if let Some(k) = &key {
        set_sz(k, "ClientId", &format_hex(&id));
    }
    id
}

/// The network last seen on an interface, from its `Status`.
pub fn last_network(ifid: &str) -> Option<String> {
    let key = interface_key(ifid)?;
    let status = status_key(&key, ifid)?;
    current(&status, "LastNetwork").filter(|s| !s.is_empty())
}

/// The machine's DUID: the registry's if written, else `generate()`'s,
/// written back.
pub fn duid(configured: Option<&[u8]>, generate: impl FnOnce() -> Vec<u8>) -> Vec<u8> {
    if let Some(d) = configured {
        return d.to_vec();
    }
    let id = generate();
    if let Some(network) = network_key() {
        set_sz(&network, "Duid", &format_hex(&id));
    }
    id
}

/// Publish the machine's readiness.
pub fn machine_readiness(level: Level) {
    if let Some(network) = network_key() {
        set_sz(&network, "Readiness", level.as_str());
    }
}

fn networks_key(id: &str) -> Option<Key> {
    let network = network_key()?;
    let (networks, _) = open_or_create(Some(&network), "Networks").ok()?;
    open_or_create(Some(&networks), id).ok().map(|(k, _)| k)
}

/// Create or refresh a network record from what was seen, and read back
/// what the operator wrote on it.
pub fn network_sync(id: &str, signals: &Signals, last_interface: &str, now_secs: i64) -> Record {
    let mut record = Record {
        id: id.to_owned(),
        ..Default::default()
    };
    let Some(key) = networks_key(id) else {
        return record;
    };
    record.name = current(&key, "Name").filter(|s| !s.is_empty());
    record.trust = current(&key, "Trust").filter(|s| !s.is_empty());
    record.requested_address = current(&key, "RequestedAddress").and_then(|s| s.parse().ok());
    if let Some(status) = status_key(&key, id) {
        set_sz(&status, "Kind", &signals.kind);
        set_opt_sz(
            &status,
            "Server",
            signals.server.map(|s| s.to_string()).as_deref(),
        );
        set_opt_sz(
            &status,
            "Gateway",
            signals.gateway.map(|g| g.to_string()).as_deref(),
        );
        set_opt_sz(
            &status,
            "Router",
            signals.router6.map(|r| r.to_string()).as_deref(),
        );
        let mut prefixes: Vec<String> = Vec::new();
        if let Some((net, p)) = signals.subnet {
            prefixes.push(format!("{net}/{p}"));
        }
        for (net, p) in &signals.prefixes6 {
            prefixes.push(format!("{net}/{p}"));
        }
        set_multi(&status, "Prefixes", &prefixes);
        let dns: Vec<String> = signals.dns.iter().map(|d| d.to_string()).collect();
        set_multi(&status, "DnsServers", &dns);
        set_sz(&status, "LastSeen", &now_secs.to_string());
        set_sz(&status, "LastInterface", last_interface);
    }
    record
}

/// The address to ask a network for next.
pub fn requested_address(id: &str) -> Option<Ipv4Addr> {
    let key = networks_key(id)?;
    current(&key, "RequestedAddress").and_then(|s| s.parse().ok())
}

/// Remember the leased address on the network for the next request.
pub fn set_requested_address(id: &str, address: Ipv4Addr) {
    if let Some(key) = networks_key(id) {
        set_sz(&key, "RequestedAddress", &address.to_string());
    }
}
