[package]
name         = "dev.peios.netd-debugsource"
architecture = "x86_64"
description  = "Exact debug sources for netd and net"

[dependencies]
"dev.peios.netd-debuginfo" = "= {{release}}"
"dev.peios.net-debuginfo"  = "= {{release}}"

[files]
"@source:LICENSE"   = "usr/share/licenses/dev.peios.netd-debugsource/LICENSE"
":licenses/**"      = "usr/share/licenses/dev.peios.netd-debugsource/third-party"
":usr/src/debug/**" = "usr/src/debug"
